name: Build Kernel - Android 13
on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: "Manually trigger the workflow"
        required: true
jobs:
  build-kernel:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          - version: "5.15"
            sub_level: 74
            os_patch_level: 2023-01
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
  
  check-build-kernel:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 189
            os_patch_level: 2023-10
          - version: "5.15"
            sub_level: 123
            os_patch_level: 2023-10
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
